{
  "name": "exception-handler",
  "version": "1.0.0",
  "description": " exception-handler",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "ts-node  Services/main.ts",
    "endPoint": "ts-node endpoint/api.ts",
    "build": "tsc"
  },
  "author": "saeed mohammed alabidi /saeed1adm@gmail.com",
  "license": "ISC",
  "keywords": [
    "CatchError"
  ],
  "devDependencies": {
    "@types/node": "^16.11.8",
    "babel-plugin-transform-typescript-metadata": "^0.3.2",
    "typescript": "^4.5.2"
  },
  "dependencies": {
    "annotation-exception-handlers": "^1.0.11",
    "automapper-ts": "^1.9.0",
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "express": "^4.17.3",
    "i": "^0.3.7",
    "npm": "^8.5.3",
    "type-identity": "^1.1.0",
    "typeorm": "^0.3.0"
  }
}
